<?

/** WARNING:  This version of squirrelmail has only been tested
    against the Cyrus imap server, and not UW.  
 **/

/* Organization's logo picture */
$org_logo = "../images/sm_logo.gif";

/* Organization's name                     */
/* Change this to your organization's name */
/* EX: Operation Mobilization              */
$org_name = "";

/* The server that your imap server is on */
$imapServerAddress = "your.host.com";
$imapPort = 143;

/* The domain where your email address is.  
 * EX:  in "luke@usa.om.org", usa.om.org is the domain.
 * this is for all the messages sent out.  Reply address
 * is generated by $username@$domain
 */
$domain = "usa.om.org";

/* Your SMTP server and port number (usually the same as the IMAP server) */
$smtpServerAddress = "your.host.com";
$smtpPort = 25;

/* This is displayed right after they log in */
$motd = "Welcome to your new webmail system running SquirrelMail.  This is not a full release, and is not a finished product.  Please visit our web site, <A HREF=\"http://squirrelmail.sourceforge.net\">squirrelmail.sourceforge.net</A>.";

/* Customizable colors
 *   These are not yet implemented
 */
$color_lgray     = "DCDCDC";
$color_red       = "800000";
$color_light_red = "FF0000";
$color_left_bg   = "A0B8C8";
$color_bground   = "FFFFFF";
$color_light_yel = "FFFFCC";

/* SquirrelMail version number -- DO NOT CHANGE */
$version = "0.1";

/* The following are related to deleting messages.
 *   $move_to_trash
 *         - if this is set to "true", when "delete" is pressed, it will attempt
 *           to move the selected messages to the folder named $trash_folder.  If
 *           it's set to "false", we won't even attempt to move the messages, just
 *           delete them.
 *   $trash_folder
 *         - This is the path to the default trash folder.  For Cyrus IMAP, it
 *           would be "INBOX.Trash", but for UW it would be "Trash".  We need the
 *           full path name here.
 *   $auto_expunge
 *         - If this is true, when a message is moved or copied, the source mailbox
 *           will get expunged, removing all messages marked "Deleted".
 */

$move_to_trash = true;
$trash_folder = "INBOX.Trash";
$auto_expunge = true;

/* Special Folders are folders that can't be manipulated like normal user created
   folders can.  A couple of examples would be "INBOX.Trash", "INBOX.Drafts".  We have
   them set to Netscape's default mailboxes, but this obviously can be changed.
   To add one, just add a new number to the array.
*/
$special_folders[0] = "INBOX";
$special_folders[1] = $trash_folder;
$special_folders[2] = "INBOX.Sent";
$special_folders[3] = "INBOX.Drafts";
$special_folders[4] = "INBOX.Templates";
?>
